wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1752220412.618887
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.13.2
      8:
      - 6
