name: pusht_image

image_shape: &image_shape [3, 128, 128]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image:
      shape: *image_shape
      type: rgb
    # agent_pos:
    #   shape: [2]
    #   type: low_dim
  action:
    shape: [7]

env_runner:
  _target_: diffusion_policy.env_runner.pusht_image_runner.PushTImageRunner
  n_train: 6
  n_train_vis: 6
  train_start_seed: 0
  n_test: 0
  n_test_vis: 4
  legacy_test: True
  test_start_seed: 100000
  max_steps: 500
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  past_action: ${past_action_visible}
  n_envs: null

dataset:
  _target_: diffusion_policy.dataset.lib_dataset.EpisodicDataset
  dataset_dir: /home/sealab/dp-yuan/CFG_diffusion_policy/diffusion_policy/data/libero_spatial
  horizon: ${horizon}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  # seed: 42
  # val_ratio: 0.02
  # max_train_episodes: 80
