wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1752219609.663043
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.13.3
      8:
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.001
